import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#E74A3B',
    },
    expcontainer:{
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#E74A3B',
      padding: 5,  // Make sure there's padding around the edges
    },
    whiteContainer: {
        backgroundColor: 'white',
        flex: 10,
        width: '90%',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        borderBottomWidth: 30,
        borderBottomColor: 'white',
        borderRadius: 15,
        marginBottom: 25,
        marginHorizontal: '5%', // Added for equal horizontal margin
    },
    greenContainer: {
        backgroundColor: 'green',
        width: '90%',
        padding: 10,
        borderRadius: 8,
        position: 'absolute',
        top: 15,
        alignItems: 'left',
    },
    greenText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    labelContainer: {
        width: '50%',
        marginBottom: 10,
    },
    labelText: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 10,
        marginTop: 20,
        color: '#1a202c',
        textAlign: 'left',
    },
    rowContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '95%',
        marginTop: 80,
    },
    rowContainer2: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '95%',
        marginTop: 10,
    },
    dropdownContainer: {
        width: '45%',
        marginBottom: 10,
        borderWidth: 0,
        maxHeight: 200,
    },

    headerContainer: {
        backgroundColor: 'white',
        paddingVertical: 5,
        paddingHorizontal: 20,
        marginVertical: 10,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginBottom: 30,
        marginTop: 60,
        marginHorizontal: '5%', // Added for equal horizontal margin
    },

    headerContainerneut: {
      backgroundColor: 'white',
      paddingVertical: 5,
      paddingHorizontal: 70,
      marginVertical: 10,
      borderRadius: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      marginBottom: 30,
      marginTop: 60,
      marginHorizontal: '5%', // Added for equal horizontal margin
  },

  headerContaineranimal: {
    backgroundColor: 'white',
    paddingVertical: 5,
    paddingHorizontal: 70,
    marginVertical: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginBottom: 30,
    marginTop: 60,
    marginHorizontal: '5%', // Added for equal horizontal margin
},

    header: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        marginTop: 30,
        marginBottom: 30,
        paddingHorizontal: 20,
        color: '#E74A3B',
    },
    headerText: {
        fontSize: 16,
        fontWeight: 'bold',
        marginTop: 20,
        marginBottom: 5,
        color: '#4a5568',
        textAlign: 'left',
    },
    textBox: {
        backgroundColor: '#F2F2F2',
        width: '90%',
        height: 40,
        borderRadius: 8,
        paddingHorizontal: 10,
        marginTop: 5,
    },
    textBox2: {
      backgroundColor: '#F2F2F2',
      width: '190%',
      height: 40,
      borderRadius: 8,
      paddingHorizontal: 10,
      marginTop: 5,
    },
    button: {
        backgroundColor: '#E74A3B',
        width: '48%',
        height: 40,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 25,
    },
    buttonexp: {
      backgroundColor: '#E74A3B',
      width: '48%',
      height: 40,
      borderRadius: 5,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 25,
  },
    buttonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    modalContainer: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        alignItems: 'center',
    },
    modalText: {
        fontSize: 18,
        marginBottom: 10,
        textAlign: 'center',
    },
    modalButton: {
        backgroundColor: '#E74A3B',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 5,
    },
    modalButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '50%',
        marginTop: 10,
    },
});

export default styles;
