import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#E74A3B',
      },
      headerContainer: {
        backgroundColor: 'white',
        paddingVertical: 5,
        paddingHorizontal: 100,
        marginVertical: 10,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginBottom: 30,
        marginTop: 60,
        marginHorizontal: '5%', // Added for equal horizontal margin
      },
      headerContainersched: {
        backgroundColor: 'white',
        paddingVertical: 5,
        paddingHorizontal: 90,
        marginVertical: 10,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginBottom: 30,
        marginTop: 60,
        marginHorizontal: '5%', // Added for equal horizontal margin
      },
      headerContainerIEC: {
        backgroundColor: 'white',
        paddingVertical: 5,
        paddingHorizontal: 120,
        marginVertical: 10,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginBottom: 30,
        marginTop: 60,
        marginHorizontal: '5%', // Added for equal horizontal margin
      },
      whiteContainer: {
        backgroundColor: 'white',
        flex: 10,
        width: '90%',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        borderBottomWidth: 30,
        borderBottomColor: 'white',
        borderRadius: 15,
        marginBottom: 25,
        marginHorizontal: '5%', // Added for equal horizont
      },
      greenContainer: {
        backgroundColor: 'green',
        width: '90%',
        padding: 10,
        borderRadius: 8,
        position: 'absolute',
        top: 15,
        alignItems: 'left',
      },
      greenText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
      },
      labelContainer: {
        width: '110%', // Adjust the width to take the full space
        marginBottom: 10,
      },
      labelText: {
        fontSize: 16,
        fontWeight: 'bold',
        marginTop: 25,
        marginBottom: 10,
        color:'#1a202c',
        textAlign: 'left',
      },
      rowContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '95%',
        marginTop: 80,
      },
      rowContainer2: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '95%',
        marginTop: 10,
      },
      dropdownContainer: {
        width: '95%',
        marginBottom: 10,
      },
      header: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        marginTop: 30,
        marginBottom: 30,
        paddingHorizontal: 20,
        color: '#E74A3B',
      },
      headerText: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 5,
        color:'#4a5568',
        textAlign: 'left',
      },
      textBox: {
        backgroundColor: '#F2F2F2',
        width: '90%',
        height: 40,
        borderRadius: 8,
        paddingHorizontal: 10,
        marginTop: 5,
      }, 
      button: {
        backgroundColor: '#E74A3B',
        width: '48%',
        height: 40,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 80,
      },
      buttonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
      },
      modalContainer: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        alignItems: 'center',
      },
      modalText: {
        fontSize: 18,
        marginBottom: 10,
        textAlign: 'center',
      },
      modalButton: {
        backgroundColor: '#E74A3B',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 5,
      },
      modalButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
      },
      modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '50%',
        marginTop: 10,
      },
});

export default styles;
